# Porta del server Spring
server.port=8080

# Config MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=officeflow
spring.jackson.serialization.write-dates-as-timestamps=false

# JWT
app.jwt.secret=questa_e_una_chiave_segreta_molto_lunga_per_officeflow_2026_security_key
app.jwt.expiration-ms=86400000
